# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

remote_theme: raviriley/agency-jekyll-theme

url    : "https://nefzi-boxingclub.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title      : Nefzi Boxingclub | Boksen Geraardsbergen 
email      : antsonlennert@gmail.com #this is also the email contact forms will go to
description: "Nefzi Boxingclub Geraardsbergen 9500, Oost-Vlaanderen, België"
author     : Lennert Antson
logo       : /assets/img/logo-transparant-cropped.png
image      : /assets/img/logo-transparant-cropped.png

facebook:
  app_id: 100063531340259
  publisher: 100063531340259
  admins: 100063531340259

social:
  name: Nefzi Boxingclub
  links:
    - https://www.facebook.com/NefziBoxingclub/
    - https://www.instagram.com/nefzi_boxing_club/
    - https://www.facebook.com/ayoub.nefzi2
    - https://www.instagram.com/ayoubnefzi1/

locale: "nl-BE" # See available languages in _data/sitetext.yml

languages:
  - "nl-BE"
  - "fr-BE"
  - "en-US"

analytics:
  google: #Google Analytics tracking code here


markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "f/mleybaqn"

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
